/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as DemoStoreRouteImport } from './routes/demo/store'
import { Route as DemoMcpTodosRouteImport } from './routes/demo/mcp-todos'
import { Route as DashboardTranscriptionRouteImport } from './routes/dashboard/transcription'
import { Route as DashboardSpeakingRouteImport } from './routes/dashboard/speaking'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardDiaryRouteImport } from './routes/dashboard/diary'
import { Route as DashboardAudioRouteImport } from './routes/dashboard/audio'
import { Route as DemoSentryTestingRouteImport } from './routes/demo/sentry.testing'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'
import { Route as DemoApiMcpTodosRouteImport } from './routes/demo/api.mcp-todos'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStoreRoute = DemoStoreRouteImport.update({
  id: '/demo/store',
  path: '/demo/store',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoMcpTodosRoute = DemoMcpTodosRouteImport.update({
  id: '/demo/mcp-todos',
  path: '/demo/mcp-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTranscriptionRoute = DashboardTranscriptionRouteImport.update({
  id: '/transcription',
  path: '/transcription',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSpeakingRoute = DashboardSpeakingRouteImport.update({
  id: '/speaking',
  path: '/speaking',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDiaryRoute = DashboardDiaryRouteImport.update({
  id: '/diary',
  path: '/diary',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAudioRoute = DashboardAudioRouteImport.update({
  id: '/audio',
  path: '/audio',
  getParentRoute: () => DashboardRoute,
} as any)
const DemoSentryTestingRoute = DemoSentryTestingRouteImport.update({
  id: '/demo/sentry/testing',
  path: '/demo/sentry/testing',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiMcpTodosRoute = DemoApiMcpTodosRouteImport.update({
  id: '/demo/api/mcp-todos',
  path: '/demo/api/mcp-todos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/mcp': typeof McpRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/dashboard/audio': typeof DashboardAudioRoute
  '/dashboard/diary': typeof DashboardDiaryRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/speaking': typeof DashboardSpeakingRoute
  '/dashboard/transcription': typeof DashboardTranscriptionRoute
  '/demo/mcp-todos': typeof DemoMcpTodosRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/demo/api/mcp-todos': typeof DemoApiMcpTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/sentry/testing': typeof DemoSentryTestingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/mcp': typeof McpRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/dashboard/audio': typeof DashboardAudioRoute
  '/dashboard/diary': typeof DashboardDiaryRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/speaking': typeof DashboardSpeakingRoute
  '/dashboard/transcription': typeof DashboardTranscriptionRoute
  '/demo/mcp-todos': typeof DemoMcpTodosRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/dashboard': typeof DashboardIndexRoute
  '/demo/api/mcp-todos': typeof DemoApiMcpTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/sentry/testing': typeof DemoSentryTestingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/mcp': typeof McpRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/dashboard/audio': typeof DashboardAudioRoute
  '/dashboard/diary': typeof DashboardDiaryRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/speaking': typeof DashboardSpeakingRoute
  '/dashboard/transcription': typeof DashboardTranscriptionRoute
  '/demo/mcp-todos': typeof DemoMcpTodosRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/demo/api/mcp-todos': typeof DemoApiMcpTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/sentry/testing': typeof DemoSentryTestingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/mcp'
    | '/signin'
    | '/signup'
    | '/dashboard/audio'
    | '/dashboard/diary'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/speaking'
    | '/dashboard/transcription'
    | '/demo/mcp-todos'
    | '/demo/store'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/dashboard/'
    | '/demo/api/mcp-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/sentry/testing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/mcp'
    | '/signin'
    | '/signup'
    | '/dashboard/audio'
    | '/dashboard/diary'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/speaking'
    | '/dashboard/transcription'
    | '/demo/mcp-todos'
    | '/demo/store'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/dashboard'
    | '/demo/api/mcp-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/sentry/testing'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard'
    | '/mcp'
    | '/signin'
    | '/signup'
    | '/dashboard/audio'
    | '/dashboard/diary'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/speaking'
    | '/dashboard/transcription'
    | '/demo/mcp-todos'
    | '/demo/store'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/dashboard/'
    | '/demo/api/mcp-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/sentry/testing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  McpRoute: typeof McpRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  DemoMcpTodosRoute: typeof DemoMcpTodosRoute
  DemoStoreRoute: typeof DemoStoreRoute
  DemoTableRoute: typeof DemoTableRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  DemoApiMcpTodosRoute: typeof DemoApiMcpTodosRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
  DemoSentryTestingRoute: typeof DemoSentryTestingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/store': {
      id: '/demo/store'
      path: '/demo/store'
      fullPath: '/demo/store'
      preLoaderRoute: typeof DemoStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/mcp-todos': {
      id: '/demo/mcp-todos'
      path: '/demo/mcp-todos'
      fullPath: '/demo/mcp-todos'
      preLoaderRoute: typeof DemoMcpTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/transcription': {
      id: '/dashboard/transcription'
      path: '/transcription'
      fullPath: '/dashboard/transcription'
      preLoaderRoute: typeof DashboardTranscriptionRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/speaking': {
      id: '/dashboard/speaking'
      path: '/speaking'
      fullPath: '/dashboard/speaking'
      preLoaderRoute: typeof DashboardSpeakingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/diary': {
      id: '/dashboard/diary'
      path: '/diary'
      fullPath: '/dashboard/diary'
      preLoaderRoute: typeof DashboardDiaryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/audio': {
      id: '/dashboard/audio'
      path: '/audio'
      fullPath: '/dashboard/audio'
      preLoaderRoute: typeof DashboardAudioRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/demo/sentry/testing': {
      id: '/demo/sentry/testing'
      path: '/demo/sentry/testing'
      fullPath: '/demo/sentry/testing'
      preLoaderRoute: typeof DemoSentryTestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/mcp-todos': {
      id: '/demo/api/mcp-todos'
      path: '/demo/api/mcp-todos'
      fullPath: '/demo/api/mcp-todos'
      preLoaderRoute: typeof DemoApiMcpTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAudioRoute: typeof DashboardAudioRoute
  DashboardDiaryRoute: typeof DashboardDiaryRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSpeakingRoute: typeof DashboardSpeakingRoute
  DashboardTranscriptionRoute: typeof DashboardTranscriptionRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAudioRoute: DashboardAudioRoute,
  DashboardDiaryRoute: DashboardDiaryRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSpeakingRoute: DashboardSpeakingRoute,
  DashboardTranscriptionRoute: DashboardTranscriptionRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRouteWithChildren,
  McpRoute: McpRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  DemoMcpTodosRoute: DemoMcpTodosRoute,
  DemoStoreRoute: DemoStoreRoute,
  DemoTableRoute: DemoTableRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  DemoApiMcpTodosRoute: DemoApiMcpTodosRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
  DemoSentryTestingRoute: DemoSentryTestingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
